### Note: Caution using importance scores in XGBoost

Why do we need the less important features, isn't the idea that less is more in machine learning?

To answer this lets use the top 3 to see what happens

In [36]:
import pandas as pd
from sklearn.model_selection import train_test_split
from xgboost import XGBClassifier

In [37]:
data = pd.read_csv("data/titanic.csv")

In [38]:
# Select our features
data = data[['Sex', 'Survived', 'Parch', 'SibSp']]

In [39]:
data.head(20)

       Sex  Survived  Parch  SibSp
0     male         0      0      1
1   female         1      0      1
2   female         1      0      0
3   female         1      0      1
4     male         0      0      0
5     male         0      0      0
6     male         0      0      0
7     male         0      1      3
8   female         1      2      0
9   female         1      0      1
10  female         1      1      1
11  female         1      0      0
12    male         0      0      0
13    male         0      5      1
14  female         0      0      0
15  female         1      0      0
16    male         0      1      4
17    male         1      0      0
18  female         0      0      1
19  female         1      0      0

In [40]:
data['Sex'] = data['Sex'].map({'male': 0, 'female': 1})

In [41]:
# looking for NaN
data.head(25)

    Sex  Survived  Parch  SibSp
0     0         0      0      1
1     1         1      0      1
2     1         1      0      0
3     1         1      0      1
4     0         0      0      0
5     0         0      0      0
6     0         0      0      0
7     0         0      1      3
8     1         1      2      0
9     1         1      0      1
10    1         1      1      1
11    1         1      0      0
12    0         0      0      0
13    0         0      5      1
14    1         0      0      0
15    1         1      0      0
16    0         0      1      4
17    0         1      0      0
18    1         0      0      1
19    1         1      0      0
20    0         0      0      0
21    0         1      0      0
22    1         1      0      0
23    0         1      0      0
24    1         0      1      3

In [42]:
# drop all missinng values in all columns
data = data.dropna()

In [44]:
X = data.drop('Survived', axis=1)
y = data['Survived']

In [45]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)

In [46]:
model = XGBClassifier()
model.fit(X_train, y_train)

XGBClassifier(base_score=0.5, booster='gbtree', callbacks=None,
              colsample_bylevel=1, colsample_bynode=1, colsample_bytree=1,
              early_stopping_rounds=None, enable_categorical=False,
              eval_metric=None, gamma=0, gpu_id=-1, grow_policy='depthwise',
              importance_type=None, interaction_constraints='',
              learning_rate=0.300000012, max_bin=256, max_cat_to_onehot=4,
              max_delta_step=0, max_depth=6, max_leaves=0, min_child_weight=1,
              missing=nan, monotone_constraints='()', n_estimators=100,
              n_jobs=0, num_parallel_tree=1, predictor='auto', random_state=0,
              reg_alpha=0, reg_lambda=1, ...)

In [47]:
y_pred = model.predict(X_test)
predictions = [round(value) for value in y_pred]

In [51]:
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, predictions)
print("Accuracy: %.2f%%" % (accuracy * 100))

Accuracy: 77.13%

Here we can see that the importance of our sex attribute isn't that low, because it causes a significant drop in 


Here we have learnt that you will have to take the feature importance parts lightly, make sure to do your own analysis, and you can use this to inform that analysis